blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/yss-tazawa/plantuml-markdown-preview/discussions
    about: For general questions that are not bug reports or feature requests.
